apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-back-app
  namespace: green-back
  labels:
    app: green-back-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-back-app
  template:
    metadata:
      name: green-back-app
      labels:
        app: green-back-app
    spec:
      containers:
        - name: green-back-app
          image: ctrlww/greenback-tg-bot:main
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: green-back-secret
          ports:
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always
      