apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-back-app
  namespace: green-back
  labels:
    app: green-back-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-back-app
  template:
    metadata:
      name: green-back-app
      labels:
        app: green-back-app
    spec:
      containers:
        - name: green-back-app
          image: green-back-image
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: green-back-secret
          ports:
            - containerPort: 5005
              protocol: TCP
          volumeMounts:
            - name: spring-application-config
              mountPath: /app/config
          resources:
            requests:
              memory: "400Mi"
              cpu: "400m"
            limits:
              memory: "600Mi"
              cpu: "500m"
      volumes:
        - name: spring-application-config
          configMap:
            name: green-back-app-config
      imagePullSecrets:
        - name: hubdocker
      restartPolicy: Always
      
