name: TEST Publish on Docker Hub and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  BOT_NAME: ${{secrets.BOT_NAME}}
  BOT_ADMIN: ${{secrets.BOT_ADMIN}}
  BOT_TOKEN: ${{secrets.BOT_TOKEN}}

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: tg-bot-service/build/libs

  build-docker:
    runs-on: ubuntu-latest
    needs:
      - build_jar
    env:
      GH_REGISTRY: "https://index.docker.io/v1"
      IMAGE_NAME: "${{ github.repository }}/greenback"
      KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
    outputs:
      container_image: ${{ env.image }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ${{ env.GH_REGISTRY }}/${{ github.repository }}

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
